# -*- coding: utf-8 -*-
"""Web Scraping Books Data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QFPH59vYnn5phgZxikwor-XsbcvSicwb
"""



import requests

url = "http://books.toscrape.com"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept-Encoding": "gzip, deflate, br",
    "Referer": "http://books.toscrape.com",
}

response = requests.get(url, headers=headers, timeout=30)

print(response.status_code)  # 200 = نجاح
print(response.text[:1000])  # طباعة أول 1000 حرف فقط لتسهيل العرض

!pip install playwright
!playwright install

import nest_asyncio
nest_asyncio.apply()

import asyncio
from playwright.async_api import async_playwright

async def scrape_books():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()
        await page.goto("http://books.toscrape.com")
        await page.wait_for_selector("article.product_pod")
        books = await page.query_selector_all("article.product_pod")

        for book in books:
            title_el = await book.query_selector("h3 > a")
            price_el = await book.query_selector(".price_color")
            title = await title_el.get_attribute("title")
            price = await price_el.inner_text()
            print(f"Title: {title} | Price: {price}")

        await browser.close()

# الآن نشغلها بهذه الطريقة في Colab
asyncio.get_event_loop().run_until_complete(scrape_books())

from bs4 import BeautifulSoup
import pandas as pd

url = "http://books.toscrape.com/"
response = requests.get(url)
response.encoding = 'utf-8'  # تصحيح الترميز
soup = BeautifulSoup(response.text, "html.parser")

books = soup.find_all("article", class_="product_pod")

data = []

for book in books:
    title = book.h3.a["title"]
    price = book.find("p", class_="price_color").text.strip()
    # إزالة ترميز غريب إن وجد (غالباً لن يحتاج في هذه الحالة)
    price = price.replace("Â", "")

    image_rel_url = book.find("img")["src"]
    image_url = "http://books.toscrape.com/" + image_rel_url.replace("../", "")

    # استخراج تقييم الكتاب من class الخاص به
    rating_class = book.find("p", class_="star-rating")["class"]
    # تقييم النصي: One, Two, Three, Four, Five
    rating = rating_class[1] if len(rating_class) > 1 else "No rating"

    data.append({
        "Title": title,
        "Price": price,
        "Rating": rating,
        "Image URL": image_url
    })

# إنشاء جدول بيانات
df = pd.DataFrame(data)

print(df)